image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1286.35543,    0.     ,  647.20352,
            0.     , 1287.2475 ,  523.22526,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.201899, 0.151606, 0.001589, -0.000909, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1229.375  ,    0.     ,  646.20349,    0.     ,
            0.     , 1247.69275,  524.41903,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
